apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: engineer02/frontend
          ports:
            - containerPort: 3000
      initContainers:
        - name: wait-for-backend
          image: busybox
          command:
            - sh
            - -c
            - >
              until nc -z backend 5050;
              do
                echo "Waiting for Backend...";
                sleep 2;
              done;
              echo "Backend is up!";
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
